### ISSUE TITLE
스켈레톤 코드 관련 질문

### ISSUE THREAD

**Issue by hamoci** [DSLDataStorage/DS_Project_2_2022_2#1]
안녕하세요. 데이터구조설계, 실습(수67)을 수강중인 2019202059 하준혁입니다.
제한 사항을 보다 질문이 생겨 이렇게 글을 씁니다.
![image](https://user-images.githubusercontent.com/55676675/199638295-5ee75e3a-ab19-46ae-803f-9566dd6392d7.png)
위의 제한사항에 따르면 형태 및 이름을 변경해서는 안되니
(1) 스켈레톤 코드로 제공된 모든 함수를 사용해야 하고,
(2) 멤버 함수들을 제거해서도 안되며, 
(3) 멤버 함수의 인자를 수정해서도 안되고,
(4) 제공된 멤버 함수의 내부 구현은 추가해도 되고,
(5) 이 외의 멤버 함수를 추가적으로 구현하는 것은 자유롭다.
즉, 이미 구조화 된 스켈레톤 코드에 대해서는 일체 수정이 불가하다라고 이해해야 하나요?
예를 들어 FPGrowth Class의 멤버 함수인 powerSet의 경우는 이름, 내부구현, 인자를 수정하면 안되고, 멤버함수 createFPtree의 인자를 수정할 수 없나요?
감사합니다.

**Comment by DSLDataStorage** [comment]
필요하시면 수정하셔도 됩니다.

**Comment by hamoci** [comment]
빠른 답변 정말 감사드립니다.
