### ISSUE TITLE
flog 소수점 입력 가능 자리수

### ISSUE THREAD

**Issue by JiNewPark** [DSLDataStorage/DS_Project_2_2022_2#10]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/112602246/201923081-aee8ddf3-a85b-4b9d-9081-7e40b7a9b284.png">
 안녕하세요. 데이터구조실습 월요일 67교시 수강중인 박진우 입니다.
위의 사진은 프로젝트 제안서의 '구현 시 반드시 정의해야하는 class 및 멤버 변수' 중에서
'1. FPGrowth : FP-Growth 클래스' 란의
'flog' 항목의 내용입니다.

 여기서 비고와 내용이 'result 파일 소수점 2자리까지만 입력 가능' 이라고 나와 있는데
result 파일은 소수점과 연관이 없어보여서 혹시 b+ tree 의 confidence를 출력하는 부분에서 confidence의 소수점 출력 제한을 이야기 하는 것인지 궁금해서 issue 남깁니다.

질문정리
(1) result 파일이 소수점과 연관이 있나요?
(2) 연관이 없다면 혹시 소수점 제한이 confidence의 소수점과 연관이 있는 건가요?

 항상 고생이 많으십니다. 감사합니다.

**Comment by DSLDataStorage** [comment]
제안서가 잘못된 것 같습니다.
1. result 파일은 소수점과 관련 없습니다.
2. 네, confidence 출력시 소수점 2자리까지 입력입니다.
   flog와 fout을 반대로 적은듯 합니다.
