### ISSUE TITLE
ERROR CODE의 출력 형식에 대해 질문

### ISSUE THREAD

**Issue by Sungjun24s** [DSLDataStorage/DS_Project_2_2022_2#11]
안녕하세요, 2019202073 박성준입니다.

PRINT_BPTREE, PRINT_RANGE, PRINT_CONFIDENCE함수에서 출력해야할 FrequentPattern이 존재하지 않을 때 log.txt파일에 다음과 같이 ERROR Code를 출력해도 되는지 궁금합니다.
![image](https://user-images.githubusercontent.com/105345819/202642518-cc754cfa-3cf8-4fdf-87e7-928dd32d9859.png)

감사합니다.

**Comment by DSLDataStorage** [comment]
네 그렇게 진행하셔도 됩니다
