### ISSUE TITLE
PRINT_CONFIDENCE 함수 관련 문의

### ISSUE THREAD

**Issue by bbbjihan** [DSLDataStorage/DS_Project_2_2022_2#3]
안녕하세요, 프로젝트 프로그램 구현 중 궁금한 점이 있어 글 남깁니다.

아래는 Functional requirements에 기재된 PRINT_CONDFIDENCE 함수의 상세내용 중 앞부분 일부입니다.
> B+-Tree에 저장된 Frequent Pattern 중 입력된 상품과 연관율 이상의 confidence 값을 가지는 Frequent Pattern을 출력하는 명령어이다. 첫 번째 인자로 상품명을 입력받고 두 번째 인자로 연관율을 받는다. 2개의 인자가 모두 입력되지 않거나 형식이 다르면 에러 코드를 출력한다.
> 연관율은 (부분집합의 빈도수)/(해당 상품의 총 빈도수) 로 계산이 된다.

이에 다음과 같은 사항을 문의드립니다.
1. 본문에서 '연관율'이라는 용어와 'confidence'라는 용어는 같은 의미로 사용되고 있는 것인가요? 예를 들어, 인용문에서 '입력된 상품과 연관율'에서 '연관율'은 PRINT_CONFIDENCE의 파라미터 중 하나인 min_confidence라고 보면 되는 건가요?
2. '연관율'과 'confidence'가 같은 용어로 쓰이고 있다면, 해당 프로젝트에서 confidence의 정의가 설계수업 시간에 교수님께서 데이터 마이닝과 관련하여 설명해주신 confidence의 정의와 다소 상이한 것으로 보이는데, 프로젝트의 정의에 따라 구현하면 되나요?
3. 연관율의 계산식에서 '해당 상품의 총 빈도수'는 '입력한 상품의 B+tree에서의 총 빈도수'와 '입력한 상품의 FP-tree에서의 총 빈도수' 중에 어떤 값인지 궁금합니다.

1번과 3번의 경우, '해당 상품의 총 빈도수'를 구하지 않아도 출력 조건에 부합하는 frequent pattern을 도출하는 방법이 기재되어 있으나 출력 양식 내에 confidence column이 포함되어 있어 값을 구하는 데에 필요하기에 여쭙니다.

감사합니다.

**Comment by DSLDataStorage** [comment]
1. 네 2번째 파라미터인 연관율은 min_confidence라고 보면 될 것 같습니다.
2. 교수님께서 수업에서 말씀하신 confidence 정의가 무엇인지 남겨주시면 좋을 것 같습니다.
3. 상품의 총 빈도수는 Transaction에서 상품의 빈도를 말합니다. 따라서 후자가 맞으며, B+Tree에 원소가 1개인 패턴은 저장하지 않으니 Header Table에서 정보를 가져오면 됩니다.

**Comment by bbbjihan** [comment]
답변 감사드립니다.
제가 본 문의를 했던 시점에서 2번을 질문드렸던 이유는 함수 인자의 개수에 차이가 있다고 생각했기 때문입니다. 좀 더 생각해보니 제가 잘못 이해하고 있었습니다. 함수 구현을 하는 데 있어서 표현을 너무 정형화해서 생각하고 있었던 것 같습니다.
다음과 같은 내용으로 구현을 하였는데, 제가 제대로 이해한 것이 맞는지 다시 질문드립니다.

프로젝트 제안서의 functional requirements에 기재된 PRINT_CONFIDENCE 함수의 상세 내용에 따르면, confidence를 구하는 데에 그 대상이 되는 item과 item을 포함하고 있는 item pattern을 필요로 합니다.

아래는 이번 학기 강의자료에서 confidence의 정의가 포함된 페이지입니다.
![image](https://user-images.githubusercontent.com/74421125/201570420-2a66cc9c-c23c-4903-8710-76a739576c58.png)

위 강의자료에서 confidence의 도출에는 2개의 set(X,Y)이 필요합니다.
저는 PRINT_CONFIDENCE 함수에서 함수의 파라미터로 입력받은 item은  위 공식에서 set X로 설정하였고, print의 대상이 될 수 있는 모든 frequent pattern을 set Y로 설정하여서 confidence를 도출하였습니다.

1. 공식을 위와 같이 해석하여 적용해도 괜찮을까요?
2. set X와 set Y의 포함관계가 가정되어 있나요? 만약 가정되어 있지 않다면, PRINT_CONFIDENCE의 파라미터로 item A를 입력하였을 때 frequent pattern 중에서 item A를 포함하지 않는 pattern에 대하여도 confidence를 구하여야 하나요?

**Comment by DSLDataStorage** [comment]
1. 
함수의 파라미터로 입력받은 item을 X로 설정하면 됩니다.
실제 confidence를 계산할 때는 itemset을 사용하지만, 제안서 요구사항은 item을 사용하기 때문에 분모에는 원소가 1개인 itemset인 item만 들어가면 됩니다.

2. 
X와 Y는 포함관계가 없습니다.
XUY이므로 item A 가 포함된 pattern에 대해서만 진행하시면 됩니다.
