### ISSUE TITLE
command.txt 형식 관련 문의드립니다.

### ISSUE THREAD

**Issue by DeV-EnCR** [DSLDataStorage/DS_Project_2_2022_2#4]
안녕하세요. 데이터구조실습(수67) 2019202068 김재윤입니다.

command.txt 에서 인자간의 구분이 whitespace인지 tab인지 궁금해서 이와 관련하여 문의드립니다.

제공된 item들을 보면 green tea, mineral water와 같이 whitespace를 포함하는 형식이 포함되어 있으며, market.txt나 result.txt에서는 data간의 구분을 tab으로 할 것이 정의되어있습니다.

그러나 command.txt의 경우 Functional Requirment의 입력 예시를 보면 인자들이 whitespace 단위로 구분되어있는 것처럼 보입니다.

PRINT_BPTREE, PRINT_CONFIDENCE, PRINT_RANGE 명령어의 경우 2개 이상의 인자를 입력받습니다.
첫 번째 인자로 문자열을 받고, 그 이후의 인자들은 숫자를 받습니다.

command.txt에서 이를 감안하여 명령어 이후 나오는 첫 번째 인자는 반드시 문자열이고, 두 번째 인자는 숫자인 점을 이용해 whitespace 단위로 인자를 tokenize할지, 
아니면 market.txt나 result.txt처럼 tab 단위로 입력해야 하는지 알고싶습니다.

**Comment by DSLDataStorage** [comment]
command.txt는 스페이스로 구분하면 되겠습니다.

**Comment by DSLDataStorage** [comment]
item 이름에 공백이 들어간 경우도 존재하니 이를 구분하기 위해 tab을 구분자로 사용하도록 하겠습니다.

**Comment by DeV-EnCR** [comment]
답변 감사합니다.
