### ISSUE TITLE
FrequentPatternNode class 관련 문의

### ISSUE THREAD

**Issue by DeV-EnCR** [DSLDataStorage/DS_Project_2_2022_2#5]
<pre>
<code>
class FrequentPatternNode
{
private:
	int frequency;		// FrequentPattern frequency
	multimap<int, set<string> > FrequentPatternList;	//first is FrequentPattern size, second is FrequentPattern data

</code>
</pre>
![image](https://user-images.githubusercontent.com/59009487/201414836-1d57a9dd-5219-4524-b67e-da7c8f757e26.png)

FrequentPatternNode의 멤버 변수인 frequency의 의미가 잘 이해되지 않아서 문의 드립니다.
1. comment 상에는 Frequent Pattern의 Frequency라고 작성되어있고,
2. Project Description PDF 상에는 Frequent Pattern의 크기로 작성되어있습니다.

1번의 경우라면 result.txt의 맨 앞의 숫자들, B+Tree에서의 element로, BpDataNode의 멤버변수인 mapData의 key가 이미 그 역할을 하고 있습니다.
2번의 경우라면 각 Frequent Pattern들을 구성하는 item들의 수(size)로,  FrequentPatternNode의 멤버변수인 FrequentPatternList의 key가 그 역할을 하고 있습니다.

그러면 frequency라는 멤버 변수가 존재하는 의미가 없지 않나 생각이 들었습니다.

아니면 혹시 frequency가 FrequentPatternList의 element의 수(size)를 나타내는 것인가요?

제가 이해한 바로는 B+Tree의 DataNode의 각 frequency마다 frequentPatternNode가 1개씩 있고, 그 내부에 frequentPatternList가 1개만 있으며, 동일한 frequency를 가지는 모든 Frequent Pattern들이 해당 frequentPatternList에 insert되는 것으로 이해하였고, 이를 바탕으로 B+Tree를 구축했습니다.

혹시 크기가 다른 frequentPattern들마다 FrequentPatternNode를 따로 생성해야하나요?
그러면 DataNode의 각 frequency마다 frequentPatternNode가 2개 이상 존재할 수 있는데, 이렇게 하는 것이 옳은 방법인가요?
제가 올바르게 이해한건지 잘 모르겠습니다.

그리고 아래는 추가 질문사항입니다.
1. FP-Growth의 Header Table의 index table을 정렬하는 method가 이미 skeleton code에 구현이 되어있는데, 별도의 수정 없이 해당 규칙대로 정렬하면 되겠습니까?

> - 인덱스 테이블에서는 빈도수를 기준으로 오름차순과 내림차순으로 정렬을 할 수 있는 함수가 구현되어야 하며, 이는 list에서 제공되는 sort 함수를 이용하여 구현한다.
> - FP-Tree에 연결되는 상품 순서는 빈도수를 기준으로 내림차순으로 결정이 되며, Header Table의 정렬 기준에 따라 결정이 된다.
> - 빈도수가 같은 경우 Header Table에서 indexTable의 정렬 기준에 따라 결정이 된다. 

구현된 descendingIndexTable()을 사용시 우선 key값을 기준으로 내림차순 정렬이 되고, 동일한 key값에서는 reverse-lexicographical하게 정렬되는 것을 확인했습니다.
동일한 key값에서 element가 입력된 순서대로 정렬하거나, 반대로 lexicographical하게 정렬되도록 람다함수를 활용하여 수정해야할지, 아니면 구현된 것 그대로 사용해야 할지 궁금합니다.

![image](https://user-images.githubusercontent.com/59009487/201416472-12b1bf77-b615-4c3f-a435-deb40929c25d.png)

2. BpTree::printFrequentPatterns()를 활용한 출력 format에 대한 질문사항입니다.
<pre>
<code>
void BpTree::printFrequentPatterns(set<string> pFrequentPattern, string item) {
	*fout << "{";
	set<string> curPattern = pFrequentPattern;
	curPattern.erase(item);
	for (set<string>::iterator it = curPattern.begin(); it != curPattern.end();) {
		string temp = *it++;
		if (temp != item) *fout << temp;
		if (it == curPattern.end()) {
			*fout << "} ";
			break;
		}
		*fout << ", ";
	}
}
</code>
</pre>

해당 함수는 set<string>으로 입력받은 하나의 Frequent Pattern을 format에 맞게 출력하는 것으로 보입니다.
curPattern에서 검색 대상의 item을 set에서 erase하는데, set은 중복을 허용하지 않으므로 item은 더이상 set에 존재하지 않습니다.
그런데 그 후 iterator로 set을 traverse하면서 temp와 item이 동일한지 비교하는 부분이 있는데 이 부분이 존재하는 이유가 궁금합니다.

또한 item을 삭제한 이유가 format에서 해당 item을 맨 앞이나 맨 뒤에 출력하기 위함으로 추측되는데, 
출력 포맷 예시를 보면 PRINT_BPTREE는 item이 맨 뒤에, PRINT_CONFIDENCE와 PRINT_RANGE는 item이 맨 앞에 출력됩니다.
맨 앞과 맨 뒤 어느 쪽으로 출력하는 것이 맞는지 궁금합니다.

4. 제공된 testcase 3의 line 287의 asparagus 앞에 whitespace가 있는데 의도하신 것인지 아니면 whitespace를 제거하는것이 맞는지 알려주시면 감사하겠습니다.

5. 가산점 부분 frequent pattern을 찾아내는 단계에서 powerSet 함수의 사용 방법을 모르겠습니다.
추측하기로는 conditional fptree를 구성할 때 부분집합을 산출하는 역할인 것 같은데, parameter의 구성이나 재귀 횟수 등이 이해하기 쉽지 않아서 가산점의 영역이지만 혹시 가능하다면 사용 방법의 힌트 라도 얻고 싶습니다.

**Comment by DSLDataStorage** [comment]
1. FrequentPatternNode의 멤버 변수인 frequency의 의미
-> 2번의 의미가 맞으며, skeleton code는 단순히 학생분들의 편의를 위해 제공되는 코드로 불필요한 부분이 있는 경우 제거하셔도 무방합니다.

2. FP-Growth의 Header Table의 index table을 정렬하는 method가 이미 skeleton code에 구현이 되어있는데, 별도의 수정 없이 해당 규칙대로 정렬하면 되겠습니까?
-> 제공한 코드 사용하시면 됩니다.

3. 또한 item을 삭제한 이유가 format에서 해당 item을 맨 앞이나 맨 뒤에 출력하기 위함으로 추측되는데,
출력 포맷 예시를 보면 PRINT_BPTREE는 item이 맨 뒤에, PRINT_CONFIDENCE와 PRINT_RANGE는 item이 맨 앞에 출력됩니다.
맨 앞과 맨 뒤 어느 쪽으로 출력하는 것이 맞는지 궁금합니다.
-> 제안서에서 명시된 대로 인자로 받은 pFrequentPattern을 그대로 출력하시면 됩니다. 해당 부분은 수정하여 올려드리겠습니다. 

4. 제공된 testcase 3의 line 287의 asparagus 앞에 whitespace가 있는데 의도하신 것인지 아니면 whitespace를 제거하는것이 맞는지
-> 제거하는 것이 맞습니다. 해당 부분은 수정하여 올려드리겠습니다.

5. 가산점 부분 frequent pattern을 찾아내는 단계에서 powerSet 함수의 사용 방법을 모르겠습니다.
-> 해당 함수가 사용되는 위치의 앞 뒤로 코드를 확인하여 잘 유추해보시길 바랍니다.
