### ISSUE TITLE
c++ compiler 문의

### ISSUE THREAD

**Issue by cosmosac** [DSLDataStorage/DS_Project_2_2022_2#6]
안녕하세요, 
제출된 코드는 테스트시  compiler에서 어떤 버전의 c++를 적용받는지 ( e.g. C++14, C++17 ,etc. ) 
궁금하여 문의 드립니다.

이상입니다.
감사합니다.

**Comment by ParkSanghyeong** [comment]
makefile을 살펴보니 C++11으로 컴파일되는 것 같습니다.
