### ISSUE TITLE
PRINT_CONFIDENCE 함수 구현 문의

### ISSUE THREAD

**Issue by hamoci** [DSLDataStorage/DS_Project_2_2022_2#7]
안녕하세요. 데이터구조설계, 실습(수67)을 수강중인 2019202059 하준혁입니다.

PRINT_CONFIDENCE 함수를 구현하면서 질문이 생겨 문의드립니다.
Frequency가 1인 경우는 Frequent Pattern에 저장되지 않으므로, Frequent Pattern만을 통해 특정 항목의 총 Frequency를 구하는 것이 불가능하다는 생각이 듭니다. 아래의 그림은 제안서의 PRINT_CONFIDENCE 함수의 출력 예시입니다.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/55676675/201620274-3df3a9dc-8fd2-4642-a983-4c03e529dbed.png">
{milk, egg}의 Frequency가 3이므로, 0.75가 나오려면 milk의 Frequency가 4임을 알아야 하는데 Frequent pattern에서는 Frequency가 1인 경우가 제외되기 때문에 milk의 정확한 Frequency를 확인할 수 없습니다.
또한 앞에서 만든 FPTree를 이용할 수 없는 것이, 실제로 B+ Tree에 대한 Test는 FPTree를 통해 만들어진 result.txt를 기반으로 하는 것이 아니라 조교님들이 특정한 result.txt를 이용하여 채점하는 것으로 알고 있습니다. 따라서 제 생각에는 특정한 항목에 대한 총 Frequency를 구할 수 없을 것 같습니다.

요약하면 아래와 같습니다.
(1) 특정한 항목(ex.milk)에 대한 총 Frequency를 구하는 것이 불가능한 것 같습니다.
(2) (1)의 이유는 Frequent Pattern에는 Frequency가 1인 경우가 저장이 되지 않기 때문입니다.
(3) 만약 총 Frequency를 구하는 것이 불가능하다면 PRINT_CONFIDENCE 함수는 특정한 항목을 포함한 Frequent Pattern 중 가장 큰 Frequency를 선택해야 할까요?

감사합니다.

**Comment by DSLDataStorage** [comment]
item에 대한 Frequency는 Header Table에서 가져오시면 됩니다.

**Comment by DSLDataStorage** [comment]
주어가 생략되어 맞는지 모르겠습니다만 B+Tree에 대한 질문이시면 맞습니다.
B+Tree를 구축하는데 사용하는 result.txt는 FPTree에서 Frequent Pattern을 추출한 결과입니다.
특정한 result.txt를 사용하는 것이 아닌 SAVE의 결과물입니다.
제안서를 확인해보시기 바랍니다.
