### ISSUE TITLE
item 중복 항목 관련 문의

### ISSUE THREAD

**Issue by bbbjihan** [DSLDataStorage/DS_Project_2_2022_2#8]
안녕하세요, 프로젝트 구현 중 궁금한 점이 있어 문의드립니다.

testcase2의 line916에서 ham이 두 번 나오는 것처럼 중복된 항목이 있을 경우
`burgers	ham	eggs	whole wheat rice	ham	french fries	cookies	green tea`
LOAD명령어 혹은 SAVE명령어 실행 시 set으로 간주하여 중복을 제거하여야 하나요?

감사합니다.

**Comment by DSLDataStorage** [comment]
중복된 아이템이 존재할 경우 중복된 값은 제거하고 진행하시면 될 것 같습니다.
