### ISSUE TITLE
스켈레톤 코드 수정 관련 질문입니다.

### ISSUE THREAD

**Issue by Sungjun24s** [DSLDataStorage/DS_Project_2_2022_2#9]
안녕하세요, 데이터구조실습 금56을 수강하고 있는 2019202073 박성준입니다.

이전 issues에서 스켈레톤 코드의 수정도 가능하다고 하셨는데,
class내의 맴버함수중 사용하지 않는 함수의 경우 삭제도 가능할까요?

예를들어 PRINT_CONFIDENCE 함수를 구현하면서 frequency와 confidence를 출력해야 할 때 BpTree class내의 맴버함수
printFrequency, printConfidence함수를 사용하지 않고 출력을 진행하였습니다. 이 경우 프로젝트를 제출 할 때 두 함수를 BpTree class에서 삭제한 후 제출해도 되는지 여쭤보고싶습니다.

**Comment by DSLDataStorage** [comment]
함수를 제거하진 마시고, 대신 기존 함수 대신에 사용한 함수에 대한 정보를 주석으로 작성바랍니다.

ex)
bool BpTree::printConfidence(string item, double item_frequency, double min_confidence)
{
/* implement in BpTree.cpp 350 lines 
or
  implement in PrintAll() function */
	return true;
}

**Comment by Sungjun24s** [comment]
답변 감사합니다.
